[package]
name = "rust_algorithm_picture_book_impl"
version = "0.1.0"
authors = ["ryota0624 <ryota.suzuki@kyash.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
